
[     UTC     ] Logs for thirdvoiceapp.streamlit.app/
────────────────────────────────────────────────────────────────────────────────────────
[21:40:46] 🚀 Starting up repository: 'thirdvoiceapp', branch: 'main', main module: 'app.py'
[21:40:46] 🐙 Cloning repository...
[21:40:47] 🐙 Cloning into '/mount/src/thirdvoiceapp'...

[21:40:47] 🐙 Cloned repository!
[21:40:47] 🐙 Pulling code changes from Github...
[21:40:48] 📦 Processing dependencies...

──────────────────────────────────────── uv ───────────────────────────────────────────

Using uv pip install.
Using Python 3.13.5 environment at /home/adminuser/venv
Resolved [2025-07-20 21:40:49.042345] 37 packages[2025-07-20 21:40:49.042663]  [2025-07-20 21:40:49.043071] in 513ms[2025-07-20 21:40:49.043565] 
Prepared 37 packages in 1.95s
Installed 37 packages in 111ms
 + altair==5.5.0
 + attrs==25.3.0
 + blinker==1.9.0
 + cachetools==6.1.0
 + certifi==2025.7.14
 + charset-normalizer==3.4.2
 + click==8.2.1
 + gitdb==4.0.12
 + gitpython==3.1.44
 + idna==3.10
 +[2025-07-20 21:40:51.108791]  jinja2==3.1.6
 + jsonschema==4.25.0
 + jsonschema-specifications==2025.4.1
 + markupsafe==3.0.2
 + narwhals==1.47.1
 +[2025-07-20 21:40:51.108979]  numpy==2.3.1
 + packaging==25.0
 + pandas==2.3.1
 + pillow==11.3.0
 + protobuf==6.31.1
 + pyarrow==21.0.0
 [2025-07-20 21:40:51.109262] + pydeck==0.9.1
 + python-dateutil==2.9.0.post0
 + pytz==2025.2
 + referencing==0.36.2
 + requests==2.32.4
 + rpds-py==0.26.0
 + six==[2025-07-20 21:40:51.109475] 1.17.0
 + smmap==5.0.2
 + streamlit==1.47.0
 + tenacity==9.1.2
 +[2025-07-20 21:40:51.109674]  toml==0.10.2
 + tornado==6.5.1
 + typing-extensions==4.14.1
 + tzdata==2025.2[2025-07-20 21:40:51.109870] 
 + urllib3==2.5.0
 + watchdog==6.0.0
Checking if Streamlit is installed
Found Streamlit version 1.47.0 in the environment
Installing rich for an improved exception logging
Using uv pip install.
Using Python 3.13.5 environment at /home/adminuser/venv
Resolved 4 packages in 140ms
Prepared 4 packages in 138ms
Installed 4 packages in 17ms
 + markdown-it-py==3.0.0
 +[2025-07-20 21:40:53.172001]  mdurl==0.1.2
 + pygments==2.19.2
 + rich==14.0.0

────────────────────────────────────────────────────────────────────────────────────────

[21:40:54] 🐍 Python dependencies were installed from /mount/src/thirdvoiceapp/requirements.txt using uv.
Check if streamlit is installed
Streamlit is already installed
[21:40:55] 📦 Processed dependencies!



2025-07-20 21:41:46.319 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:41:48.580 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:42:07.937 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:42:09.818 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:42:20.281 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:42:25.645 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:42:48.319 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:42:48.394 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:43:21.558 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:43:23.301 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:44:01.255 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:44:03.007 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:44:07.355 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:45:49.633 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:50:49.661 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 21:55:49.642 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:00:49.646 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    main()
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    user_input = st.text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
[22:04:57] 🐙 Pulling code changes from Github...
[22:04:57] 📦 Processing dependencies...
[22:04:57] 📦 Processed dependencies!
[22:04:59] 🔄 Updated app!
2025-07-20 22:05:25.508 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:29.400 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:31.459 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:33.221 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:34.788 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:36.380 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:49.603 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:50.950 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(
2025-07-20 22:05:50.988 `label` got an empty value. This is discouraged for accessibility reasons and may be disallowed in the future by raising an exception. Please provide a non-empty label and hide it with label_visibility if needed.
Stack (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1014, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 378, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 685, in _run_script
    ) = exec_func_with_error_handling(code_to_exec, ctx)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
  File "/mount/src/thirdvoiceapp/app.py", line 448, in <module>
    <h4 style="margin-top: 0; color: #1f2937;">{action_icon} {action_title}</h4>
  File "/mount/src/thirdvoiceapp/app.py", line 289, in main
    return None, "Request timed out. Please try again."
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/runtime/metrics_util.py", line 443, in wrapped_func
    result = non_optional_func(*args, **kwargs)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 596, in text_area
    return self._text_area(
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/widgets/text_widgets.py", line 639, in _text_area
    maybe_raise_label_warnings(label, label_visibility)
  File "/home/adminuser/venv/lib/python3.13/site-packages/streamlit/elements/lib/policies.py", line 184, in maybe_raise_label_warnings
    _LOGGER.warning(